; vim: ft=asm_ca65
_vdp_80_col              = $FF48
_vdp_unlock              = $FF4B
_vdp_lock                = $FF4E
_vdp_print               = $FF51
_vdp_clear_screen        = $FF54
_vdp_init_textmode       = $FF57
_vdp_write_reg           = $FF5A
_vdp_write_address       = $FF5D
_vdp_load_font           = $FF60
_vdp_newline             = $FF63
_vdp_write_char          = $FF66
_vdp_console_out         = $FF69

