sfs_init                   = $FF18
sfs_mount                  = $FF1B
sfs_open_first_index_block = $FF1E
sfs_create                 = $FF21
sfs_find                   = $FF24
sfs_read_next_index        = $FF27
sfs_write                  = $FF2A
sfs_read                   = $FF2D
sfs_delete                 = $FF30
sfs_format                 = $FF33
sfs_open                   = $FF36
sfs_close                  = $FF39
sfs_read_byte              = $FF3C
sfs_write_byte             = $FF3F
sdcard_init                = $FF42
dos_bdir                   = $FF45

sfs_errno = $B252